// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageStore_Save_FullMethodName      = "/message.MessageStore/Save"
	MessageStore_GetLast10_FullMethodName = "/message.MessageStore/GetLast10"
)

// MessageStoreClient is the client API for MessageStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageStoreClient interface {
	Save(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
	GetLast10(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*MessageList, error)
}

type messageStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageStoreClient(cc grpc.ClientConnInterface) MessageStoreClient {
	return &messageStoreClient{cc}
}

func (c *messageStoreClient) Save(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MessageStore_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageStoreClient) GetLast10(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*MessageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageList)
	err := c.cc.Invoke(ctx, MessageStore_GetLast10_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageStoreServer is the server API for MessageStore service.
// All implementations must embed UnimplementedMessageStoreServer
// for forward compatibility.
type MessageStoreServer interface {
	Save(context.Context, *Message) (*Empty, error)
	GetLast10(context.Context, *UserRequest) (*MessageList, error)
	mustEmbedUnimplementedMessageStoreServer()
}

// UnimplementedMessageStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageStoreServer struct{}

func (UnimplementedMessageStoreServer) Save(context.Context, *Message) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedMessageStoreServer) GetLast10(context.Context, *UserRequest) (*MessageList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLast10 not implemented")
}
func (UnimplementedMessageStoreServer) mustEmbedUnimplementedMessageStoreServer() {}
func (UnimplementedMessageStoreServer) testEmbeddedByValue()                      {}

// UnsafeMessageStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageStoreServer will
// result in compilation errors.
type UnsafeMessageStoreServer interface {
	mustEmbedUnimplementedMessageStoreServer()
}

func RegisterMessageStoreServer(s grpc.ServiceRegistrar, srv MessageStoreServer) {
	// If the following call panics, it indicates UnimplementedMessageStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageStore_ServiceDesc, srv)
}

func _MessageStore_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageStoreServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageStore_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageStoreServer).Save(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageStore_GetLast10_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageStoreServer).GetLast10(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageStore_GetLast10_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageStoreServer).GetLast10(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageStore_ServiceDesc is the grpc.ServiceDesc for MessageStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageStore",
	HandlerType: (*MessageStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _MessageStore_Save_Handler,
		},
		{
			MethodName: "GetLast10",
			Handler:    _MessageStore_GetLast10_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
